let POSTS=[];
const POST_FILES=["data/posts-1.json","data/posts-2.json","data/posts-3.json","data/posts-4.json","data/posts-5.json","data/posts-6.json"];
const CATEGORIES=['Toutes les voix','Intelligence artificielle','Quantique & sciences','Politique & monde','Économie & société','Robotique & énergie','Histoire & culture','Archives'];
const state={query:'',category:'Toutes les voix',limit:12};
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const date=v=>v?new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'Date inconnue';
function home(){const normalized=state.query.trim().toLocaleLowerCase('fr-FR');const filtered=POSTS.filter(p=>(state.category==='Toutes les voix'||p.categories.includes(state.category))&&(!normalized||(p.title+' '+p.excerpt+' '+p.categories.join(' ')).toLocaleLowerCase('fr-FR').includes(normalized)));const visible=filtered.slice(0,state.limit);document.title='AROBASIX BIS — Les idées en mouvement';document.getElementById('app').innerHTML=`<section class="hero"><div><p class="eyebrow">● Science-fiction · politique-fiction · économie · société</p><h1>Les idées<br><em>en mouvement.</em></h1><p class="hero-copy">AROBASIX BIS reprend l’intégralité de l’archive publiée depuis 2007 et la rend plus simple à parcourir, à relire et à enrichir.</p></div><aside class="hero-note"><span class="eyebrow">BIS / 01</span><h2>Une archive personnelle, devenue un lieu de lecture.</h2><div class="stats"><div><strong>${POSTS.length}</strong><small>articles repris</small></div><div><strong>2007–26</strong><small>période couverte</small></div></div></aside></section><section id="archives" class="archive"><div class="archive-inner"><div class="tools"><div><p class="eyebrow">01 / Parcourir</p><h2 class="section-title">L’archive, par le fil des idées</h2></div><input id="search" class="search" value="${esc(state.query)}" placeholder="Rechercher un titre ou un mot…" aria-label="Rechercher dans les archives"></div><div class="filters">${CATEGORIES.map(c=>`<button class="filter ${c===state.category?'active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('')}</div><p class="results-count">${filtered.length} résultat${filtered.length>1?'s':''}</p><div class="grid">${visible.map(card).join('')}</div>${filtered.length>visible.length?`<button id="more" class="load-more">Afficher les ${filtered.length-visible.length} articles suivants</button>`:''}</div></section><section id="methode" class="method"><div class="method-inner"><div><p class="eyebrow">02 / Recommandations</p><h2 class="section-title">Garder la voix.<br><em>Clarifier le chemin.</em></h2><p class="hero-copy">Le contenu reste celui d’AROBASIX. La structure ajoute des repères sans lisser le ton ni réécrire les prises de position.</p></div><div class="recommendations">${[['01','Thèmes transversaux','Chaque article est classé par grandes familles pour rendre les 115 entrées découvrables.'],['02','Pages lisibles','La date, les médias, les liens et la source Blogger restent accessibles.'],['03','Archive durable','Le catalogue peut être synchronisé à nouveau depuis Blogger.'],['04','Publication prudente','Images et GIF sont conservés ; les scripts exécutables sont neutralisés.']].map(x=>`<div class="recommendation"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div></div></section>`;bindHome();}
function card(p){return `<article class="card"><div class="card-meta"><time>${date(p.published)}</time><span class="tag">${esc(p.categories[0])}</span></div><h3><a href="#article=${encodeURIComponent(p.slug)}">${esc(p.title)}</a></h3><p>${esc(p.excerpt||'Article importé depuis l’archive AROBASIX.')}</p><div class="card-footer"><span>${p.imageCount} média${p.imageCount>1?'s':''}</span><span>·</span><span>${p.linkCount} lien${p.linkCount>1?'s':''}</span></div><a class="read" href="#article=${encodeURIComponent(p.slug)}">Lire l’article ↗</a></article>`}
function bindHome(){document.getElementById('search').addEventListener('input',e=>{state.query=e.target.value;state.limit=12;home();requestAnimationFrame(()=>document.getElementById('search')?.focus())});document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;state.limit=12;home();location.hash='archives'}));document.getElementById('more')?.addEventListener('click',()=>{state.limit+=24;home();location.hash='archives'})}
function article(slug){const p=POSTS.find(x=>x.slug===slug);if(!p){home();return}document.title=p.title+' — AROBASIX BIS';document.getElementById('app').innerHTML=`<article class="article"><a class="back" href="#archives">← Toutes les archives</a><p class="eyebrow" style="margin-top:45px">${date(p.published)} · ${p.categories.map(esc).join(' · ')}</p><h1>${esc(p.title)}</h1><div class="article-meta"><span>${p.imageCount} média${p.imageCount>1?'s':''}</span><span>${p.linkCount} lien${p.linkCount>1?'s':''}</span><a href="${esc(p.url)}" target="_blank" rel="noreferrer">Voir l’original Blogger ↗</a></div><div class="prose">${p.html}</div><p class="legacy">Reprise depuis l’archive AROBASIX. Les images, GIF, liens et médias intégrés sont conservés ; les scripts exécutables ont été neutralisés.</p></article>`;scrollTo(0,0)}
function route(){const m=location.hash.match(/^#article=(.+)$/);m?article(decodeURIComponent(m[1])):home()}
async function boot(){try{const batches=await Promise.all(POST_FILES.map(file=>fetch(file).then(response=>{if(!response.ok)throw new Error(file);return response.json()})));POSTS=batches.flat();addEventListener('hashchange',route);route()}catch(error){document.getElementById('app').innerHTML='<section class="article"><h1>Archive momentanément indisponible</h1><p>Les données des articles n’ont pas pu être chargées.</p></section>';console.error(error)}}
boot();